### ISSUE TITLE
Github Ticket Updating

### ISSUE THREAD

**Issue by ncipollo** [ncipollo/tix#36]
In this issue we will add support for updating existing github tickets.

---

**Todo**
- [ ] Create a settings key which indicates the ticket should be updated (something like `update_ticket`). The value can be the ticket id to update.
- [ ] Add general flag to the `ticket.Ticket` which indicates update vs create.
- [ ] Add update method(s) to api. We will likely need a method for issues and one for projects
- [ ] Add mechanism to creator & friends to update the ticket instead of creating it if this flag is set.
